In [1]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn import linear_model

In [2]:
def polynomial_dataframe(feature, degree): # feature is pandas.Series type
    # assume that degree >= 1
    # initialize the dataframe:
    poly_dataframe = pd.DataFrame()
    # and set poly_dataframe['power_1'] equal to the passed feature
    poly_dataframe['power_1'] = feature
    # first check if degree > 1
    if degree > 1:
        # then loop over the remaining degrees:
        for power in range(2, degree+1):vc                  v
            # first we'll give the column a name:
            name = 'power_' + str(power)
            previous_name = 'power_' + str(power-1)
            # assign poly_dataframe[name] to be feature^power; use apply(*)
            poly_dataframe[name] = poly_dataframe[previous_name]*poly_dataframe['power_1']
    return poly_dataframe

In [3]:
import pandas as pd

dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':float, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}

sales = pd.read_csv('kc_house_data.csv', dtype=dtype_dict)
sales = sales.sort(['sqft_living','price'])

C:\Users\Dejucoder\Miniconda3\lib\site-packages\ipykernel\__main__.py:6: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


In [4]:
l2_small_penalty = 1.5e-5

In [7]:
poly15_data = polynomial_dataframe(sales['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model.fit(poly15_data, sales['price'])
model.coef_

array([  1.24873306e+02,  -4.77376011e-02,   3.01446238e-05,
        -2.44419942e-09,  -1.94153675e-13,   8.54085686e-18,
         1.51142121e-21,   8.27979094e-26,   6.52603100e-31,
        -3.27895017e-34,  -3.87962315e-38,  -2.72437650e-42,
        -1.07790800e-46,   3.78242694e-51,   1.39790296e-54])

In [8]:
set_1 = pd.read_csv('wk3_kc_house_set_1_data.csv', dtype=dtype_dict)
set_2 = pd.read_csv('wk3_kc_house_set_2_data.csv', dtype=dtype_dict)
set_3 = pd.read_csv('wk3_kc_house_set_3_data.csv', dtype=dtype_dict)
set_4 = pd.read_csv('wk3_kc_house_set_4_data.csv', dtype=dtype_dict)

In [9]:
l2_small_penalty = 1e-9

In [10]:
#set 1
poly15_data_set1 = polynomial_dataframe(set_1['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model_set1 = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model_set1.fit(poly15_data_set1, set_1['price'])
model_set1.coef_

array([  5.44669414e+02,  -3.55447623e-01,   1.22446391e-04,
        -1.17175343e-08,  -3.90512062e-13,  -1.39076372e-17,
         1.47860262e-20,   6.87492108e-25,  -7.57203963e-29,
        -1.04097309e-32,  -3.71844145e-37,   3.39989269e-41,
         5.56592085e-45,   2.53761354e-49,  -3.35152908e-53])

In [12]:
#set 2
poly15_data_set2 = polynomial_dataframe(set_2['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model_set2 = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model_set2.fit(poly15_data_set2, set_2['price'])
model_set2.coef_

array([  8.59362622e+02,  -8.18118239e-01,   4.28879955e-04,
        -9.12770557e-08,  -2.69604593e-12,   3.73980308e-15,
        -1.42711860e-19,  -6.30794712e-23,  -1.44559666e-27,
         7.44321303e-31,   9.25866168e-35,   3.27972417e-41,
        -1.29543486e-42,  -1.38781260e-46,   1.66546444e-50])

In [13]:
#set 3
poly15_data_set3 = polynomial_dataframe(set_3['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model_set3 = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model_set3.fit(poly15_data_set3, set_3['price'])
model_set3.coef_

array([ -7.55395926e+02,   9.75579507e-01,  -4.58945996e-04,
         7.77958131e-08,   7.15013236e-12,  -2.88601960e-15,
        -2.13678198e-20,   3.38085265e-23,   2.19178098e-27,
        -1.97067737e-31,  -4.15993064e-35,  -1.80196269e-39,
         3.19071142e-43,   5.08456951e-47,  -3.93304268e-51])

In [14]:
#set 4
poly15_data_set4 = polynomial_dataframe(set_4['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model_set4 = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model_set4.fit(poly15_data_set4, set_4['price'])
model_set4.coef_

array([  1.11944571e+03,  -9.83760201e-01,   3.38770888e-04,
         3.60377230e-08,  -4.37814006e-11,   5.77191612e-15,
         7.66795410e-19,  -9.49297933e-23,  -1.96030773e-26,
        -2.10888286e-32,   3.31005081e-34,   3.47734014e-38,
        -2.43039413e-42,  -8.79553278e-46,   6.44569716e-50])

In [15]:
l2_large_penalty=1.23e2

In [16]:
#set 1
model_set1_penalised = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model_set1_penalised.fit(poly15_data_set1, set_1['price'])
model_set1_penalised.coef_

array([  2.32806803e+00,   3.53621608e-04,   3.31969692e-08,
         2.00082477e-12,   1.11492559e-16,   6.57786122e-21,
         4.12939525e-25,   2.70393755e-29,   1.81614763e-33,
         1.23824277e-37,   8.51872481e-42,   5.89455598e-46,
         4.09542560e-50,   2.85464889e-54,   1.99547476e-58])

In [17]:
#set 2
model_set2_penalised = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model_set2_penalised.fit(poly15_data_set2, set_2['price'])
model_set2_penalised.coef_

array([  2.09756903e+00,   3.90817483e-04,   6.67189944e-08,
         8.90002997e-12,   9.72639877e-16,   9.69733682e-20,
         9.50564475e-24,   9.44491031e-28,   9.57191338e-32,
         9.86945155e-36,   1.03101115e-39,   1.08729784e-43,
         1.15453748e-47,   1.23211305e-51,   1.31986696e-55])

In [18]:
#set 3
model_set3_penalised = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model_set3_penalised.fit(poly15_data_set3, set_3['price'])
model_set3_penalised.coef_

array([  2.28906258e+00,   4.12472190e-04,   6.08835345e-08,
         6.58572163e-12,   6.15278155e-16,   5.64446634e-20,
         5.28834396e-24,   5.07091402e-28,   4.94657273e-32,
         4.88043809e-36,   4.85009106e-40,   4.84161534e-44,
         4.84635021e-48,   4.85883628e-52,   4.87558469e-56])

In [19]:
#set 4
model_set4_penalised = linear_model.Ridge(alpha=l2_large_penalty, normalize=True)
model_set4_penalised.fit(poly15_data_set4, set_4['price'])
model_set4_penalised.coef_

array([  2.08596194e+00,   4.05035772e-04,   7.46864647e-08,
         1.13096608e-11,   1.45864442e-15,   1.73561251e-19,
         2.01609632e-23,   2.34605255e-27,   2.75636073e-31,
         3.27043069e-35,   3.91046855e-39,   4.70118041e-43,
         5.67212304e-47,   6.85958087e-51,   8.30843630e-55])

In [20]:
train_valid_shuffled = pd.read_csv('wk3_kc_house_train_valid_shuffled.csv', dtype=dtype_dict)
test = pd.read_csv('wk3_kc_house_test_data.csv', dtype=dtype_dict)

In [24]:
n = len(train_valid_shuffled)
k = 10 # 10-fold cross-validation

for i in range(k):
    start = (n*i)//k
    end = (n*(i+1))//k-1
    print (i, (start, end))

0 (0, 1938)
1 (1939, 3878)
2 (3879, 5817)
3 (5818, 7757)
4 (7758, 9697)
5 (9698, 11636)
6 (11637, 13576)
7 (13577, 15515)
8 (15516, 17455)
9 (17456, 19395)


In [67]:
def k_fold_cross_validation(k, l2_penalty, data, output):
    n , RSS= len(data), 0
    for i in range(k) :
        start, end = (n*i)//k, (n*(i+1))//k-1
        cv_data = data[start:end+1]
        cv_output = output[start:end+1]
        if i==0 :
            train_data = data[end+1:n]
            train_output = output[end+1:n]
        elif i==k-1 :
            train_data = data[0:start]
            train_output = output[0:start]
        else :
            train_data = data[0:start]
            train_data.append(data[end+1:n])
            train_output = output[0:start]
            train_output.append(output[end+1:n])
        model = linear_model.Ridge(alpha=l2_penalty, normalize=True)
        model.fit(train_data,train_output)
        predictions = model.predict(cv_data)
        RSS += sum((predictions-cv_output)*(predictions-cv_output))
    average_validation_error = RSS / n
    return [average_validation_error]

In [68]:
data = polynomial_dataframe(train_valid_shuffled['sqft_living'], 15)
k=10
for l2_penalty in np.logspace(3, 9, num=13) :
    error = k_fold_cross_validation(k,l2_penalty,data[0:19392],train_valid_shuffled['price'])
    print(error)

[136508762048.42165]
[136871340111.74513]
[137074672944.09927]
[137148119920.92538]
[137172269679.72435]
[137179999170.17101]
[137182452725.39919]
[137183229535.54927]
[137183475277.28296]
[137183552996.92226]
[137183577574.95813]
[137183585347.30832]
[137183587805.15057]


In [72]:
final_model = linear_model.Ridge(alpha=1000.00, normalize=True)
test_data = polynomial_dataframe(test['sqft_living'], 15)
final_model.fit(data,train_valid_shuffled['price'])
predictions = model.predict(test_data)
RSS = sum((predictions-test['price'])*(predictions-test['price']))
print(RSS)

1.32816787077e+14
