In [9]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn import linear_model

In [16]:
def polynomial_dataframe(feature, degree): # feature is pandas.Series type
    # assume that degree >= 1
    # initialize the dataframe:
    poly_dataframe = pd.DataFrame()
    # and set poly_dataframe['power_1'] equal to the passed feature
    poly_dataframe['power_1'] = feature
    # first check if degree > 1
    if degree > 1:
        # then loop over the remaining degrees:
        for power in range(2, degree+1):
            # first we'll give the column a name:
            name = 'power_' + str(power)
            previous_name = 'power_' + str(power-1)
            # assign poly_dataframe[name] to be feature^power; use apply(*)
            poly_dataframe[name] = poly_dataframe[previous_name]*poly_dataframe['power_1']
    return poly_dataframe

In [17]:
sales = pd.read_csv('kc_house_data.csv')
sales = sales.sort(['sqft_living','price'])

C:\Users\Dejucoder\Miniconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


In [29]:
poly1_data = polynomial_dataframe(sales['sqft_living'], 1)
poly1_data['price'] = sales['price']

In [31]:
model1 = linear_model.LinearRegression()
model1.fit(poly1_data[['power_1']] , poly1_data['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
plt.scatter(poly1_data['power_1'],poly1_data['price'])
plt.plot(poly1_data['power_1'] , model1.predict(poly1_data[['power_1']]))
plt.show()

In [34]:
poly2_data = polynomial_dataframe(sales['sqft_living'], 2)
poly2_data['price'] = sales['price']
model2 = linear_model.LinearRegression()
model2.fit(poly2_data[['power_1','power_2']] , poly2_data['price'])
plt.scatter(poly2_data['power_1'],poly2_data['price'])
plt.plot(poly2_data['power_1'] , model2.predict(poly2_data[['power_1','power_2']]))
plt.show()

In [36]:
l = ['power_1','power_2','power_3','power_4','power_5','power_6','power_7','power_8','power_9','power_10','power_11','power_12','power_13','power_14','power_15']
poly15_data = polynomial_dataframe(sales['sqft_living'], 15)
poly15_data['price'] = sales['price']
model15 = linear_model.LinearRegression()
model15.fit(poly15_data[l] , poly15_data['price'])
plt.scatter(poly15_data['power_1'],poly15_data['price'])
plt.plot(poly15_data['power_1'] , model15.predict(poly15_data[l]))
plt.show()

In [37]:
set_1 = pd.read_csv('wk3_kc_house_set_1_data.csv')
set_2 = pd.read_csv('wk3_kc_house_set_2_data.csv')
set_3 = pd.read_csv('wk3_kc_house_set_3_data.csv')
set_4 = pd.read_csv('wk3_kc_house_set_4_data.csv')

In [46]:
#SET 1
l = ['power_1','power_2','power_3','power_4','power_5','power_6','power_7','power_8','power_9','power_10','power_11','power_12','power_13','power_14','power_15']
poly15_data = polynomial_dataframe(set_1['sqft_living'], 15)
poly15_data['price'] = set_1['price']
model15 = linear_model.LinearRegression()
model15.fit(poly15_data[l] , poly15_data['price'])
plt.scatter(poly15_data['power_1'],poly15_data['price'])
plt.plot(poly15_data['power_1'] , model15.predict(poly15_data[l]))
plt.show()
model15.coef_

array([  1.76406399e-05,   4.45333757e-02,   4.13849787e-06,
        -4.48147185e-10,  -2.26282860e-14,   1.01081727e-16,
        -7.24309809e-16,   2.86983005e-16,  -1.74329860e-16,
        -1.27118543e-15,   1.16875637e-16,   5.53624437e-16,
         1.98532723e-16,  -3.19799824e-16,  -3.84117144e-16])

In [47]:
#SET 2
l = ['power_1','power_2','power_3','power_4','power_5','power_6','power_7','power_8','power_9','power_10','power_11','power_12','power_13','power_14','power_15']
poly15_data = polynomial_dataframe(set_2['sqft_living'], 15)
poly15_data['price'] = set_2['price']
model15 = linear_model.LinearRegression()
model15.fit(poly15_data[l] , poly15_data['price'])
plt.scatter(poly15_data['power_1'],poly15_data['price'])
plt.plot(poly15_data['power_1'] , model15.predict(poly15_data[l]))
plt.show()
model15.coef_

array([  3.00887122e-05,   6.13527083e-02,  -2.50166625e-06,
         1.10934186e-10,  -1.76936161e-14,   8.00549083e-16,
        -3.62863067e-16,  -3.03139972e-16,  -6.11465644e-16,
         3.72088850e-16,   7.10876405e-16,   7.73061133e-16,
         1.03734364e-15,  -4.76399540e-16,   1.34602300e-15])

In [48]:
#SET 3
l = ['power_1','power_2','power_3','power_4','power_5','power_6','power_7','power_8','power_9','power_10','power_11','power_12','power_13','power_14','power_15']
poly15_data = polynomial_dataframe(set_3['sqft_living'], 15)
poly15_data['price'] = set_3['price']
model15 = linear_model.LinearRegression()
model15.fit(poly15_data[l] , poly15_data['price'])
plt.scatter(poly15_data['power_1'],poly15_data['price'])
plt.plot(poly15_data['power_1'] , model15.predict(poly15_data[l]))
plt.show()
model15.coef_

array([  3.05361076e-05,   6.76638174e-02,  -5.32878619e-06,
         4.59965794e-10,  -1.31916227e-14,  -1.53508100e-16,
        -3.52183027e-16,   5.71978479e-16,   4.35381696e-16,
         5.29539474e-16,  -2.22894208e-16,   1.12007909e-15,
         6.01719848e-16,   3.26682930e-16,  -2.48656137e-16])

In [49]:
#SET 4
l = ['power_1','power_2','power_3','power_4','power_5','power_6','power_7','power_8','power_9','power_10','power_11','power_12','power_13','power_14','power_15']
poly15_data = polynomial_dataframe(set_4['sqft_living'], 15)
poly15_data['price'] = set_4['price']
model15 = linear_model.LinearRegression()
model15.fit(poly15_data[l] , poly15_data['price'])
plt.scatter(poly15_data['power_1'],poly15_data['price'])
plt.plot(poly15_data['power_1'] , model15.predict(poly15_data[l]))
plt.show()
model15.coef_

array([  2.93118439e-05,   5.47886719e-02,  -1.44597326e-06,
         7.43466678e-11,   3.46579476e-14,  -1.23517408e-15,
        -4.06166035e-16,   8.99235660e-16,  -4.91634692e-16,
        -5.41357731e-16,   2.78692453e-16,   3.96326115e-16,
         2.88541057e-16,  -1.03623740e-15,  -3.32596167e-16])

In [51]:
train_data = pd.read_csv('wk3_kc_house_train_data.csv')
cv_data = pd.read_csv('wk3_kc_house_valid_data.csv')
test_data = pd.read_csv('wk3_kc_house_test_data.csv')

In [60]:
l = []
RSS=[]
for degree in range(1,16) :
    name = 'power_' + str(degree)
    l.append(name)
    poly_data = polynomial_dataframe(train_data['sqft_living'], degree)
    poly_data['price'] = train_data['price']
    poly_data_cv = polynomial_dataframe(cv_data['sqft_living'], degree)
    poly_data_cv['price'] = cv_data['price']
    poly_data_test = polynomial_dataframe(test_data['sqft_living'], degree)
    poly_data_test['price'] = test_data['price']
    
    model = linear_model.LinearRegression()
    model.fit(poly_data[l] , poly_data['price'])
    predictions = model.predict(poly_data_cv[l])
    error = predictions - poly_data_cv['price']
    RSS.append(sum(error*error))
print(RSS)

[629097886299587.5, 623955062706519.0, 625820280251626.38, 629987338893925.13, 623376391568332.5, 623259997611469.63, 623154755574664.25, 623383991540182.25, 623342662556829.75, 623337345463238.38, 623592184944468.75, 623362156304389.88, 623353409828896.63, 623280835820432.88, 623365679974166.63]


In [62]:
poly_data = polynomial_dataframe(train_data['sqft_living'], 6)
poly_data['price'] = train_data['price']
poly_data_cv = polynomial_dataframe(cv_data['sqft_living'], 6)
poly_data_cv['price'] = cv_data['price']
poly_data_test = polynomial_dataframe(test_data['sqft_living'], 6)
poly_data_test['price'] = test_data['price']
l=['power_1','power_2','power_3','power_4','power_5','power_6']   
model = linear_model.LinearRegression()
model.fit(poly_data[l] , poly_data['price'])
predictions = model.predict(poly_data_test[l])
error = predictions - poly_data_test['price']
print(sum(error*error))

1.367677461e+14
